### ISSUE TITLE
Training video results in an error in data.py

### ISSUE THREAD

**Issue by cedonley** [2U1/Qwen2-VL-Finetune#1]
Hello - I notice that when I try to train with data formatted like the video example, I get the following error:

  File "/ai/train/Qwen2-VL-Finetune/src/training/data.py", line 181, in __getitem__
    all_pixel_values.append(inputs['pixel_values'])
  File "/ai/miniconda3/envs/qwen2/lib/python3.10/site-packages/transformers/feature_extraction_utils.py", line 87, in __getitem__
    return self.data[item]
KeyError: 'pixel_values'

I notice that input contains 'pixel_values_videos' and not pixel_values. It seems that part of the functionality for handing video inputs is missing in the version that is committed. Thanks!

**Comment by 2U1** [comment]
Thnks for reporting the bug! 
I've fixed the code for video data and tested. It works well now. Sorry for the inconvinience.

**Comment by cedonley** [comment]
Hi. That fixed the data processing error and things are getting closer, but now get a different error when it processes same data. 

  File "/ai/miniconda3/envs/qwen2/lib/python3.10/site-packages/liger_kernel/transformers/model/qwen2_vl.py", line 115, in lce_forward
    inputs_embeds[video_mask] = video_embeds
RuntimeError: shape mismatch: value tensor of shape [2376, 3584] cannot be broadcast to indexing result of shape [0, 3584]

If you think this is unrelated to how you've processed the data, then I can open a new issue on it. Happy to try something to help debug if necessary. Thanks!

**Comment by 2U1** [comment]
@cedonley It's wierd that I've tested and it was alright.
Does the video data of yours looks like this? I've made the code for the video as `<video>` .
```
[
  {
    "id": "sample1",
    "video": "sample1.mp4",
    "conversations": [
      {
        "from": "human",
        "value": "<video>\nWhat is going on in this video?"
      },
      {
        "from": "gpt",
        "value": "A man is walking down the road."
      }
    ]
  }
  ...
]
```

**Comment by cedonley** [comment]
Ok. I discovered that the "\n" is critical after the "<video>" tag. I had modified this from another dataset that I was using with a different tool (LlamaFactory) and had not noticed that it was being used as a separator. I'm now running into OOM on even a single 10 second 1fps 320x240 video on an A6000, but will look into that this evening when I have time.

**Comment by 2U1** [comment]
I'm using the exact same format from LLaVA so, I made to parse with it.
I'm debugging the problem of using too much vram too. Let me know if you get it.

**Comment by 2U1** [comment]
Closing the issue for no other comments.
