### ISSUE TITLE
Can it support data without images or videos?

### ISSUE THREAD

**Issue by kike-0304** [2U1/Qwen2-VL-Finetune#11]

**Comment by 2U1** [comment]
Yes it does but, I'm not sure it can handle mixed dataset.

**Comment by kike-0304** [comment]
> Yes it does but, I'm not sure it can handle mixed dataset.

The dataset without images or videos will report an error, indicating that there is no 'pixel_key'“ in data.py.

**Comment by 2U1** [comment]
@kike-0304 Sorry, I've was a bit confused with other repo I made. I think it will available now.

**Comment by kike-0304** [comment]
> @kike-0304 Sorry, I've was a bit confused with other repo I made. I think it will available now.

keyerror: 'Indexing with integers is not available when using Python based feature extractors. in data.py line 189
