### ISSUE TITLE
format object detection use Qwen2-VL-Finetune 

### ISSUE THREAD

**Issue by xjohnxjohn** [2U1/Qwen2-VL-Finetune#15]
Can i use the <ref></ref> and <box></box> for object detection in dataset format?

**Comment by 2U1** [comment]
I'm not sure about that. The original model has learned from the object detecting dataset so I think you could.

**Comment by gaussiangit** [comment]
@2U1 for object detection just add bounding box in the response ? or some special format ? do you have an example ?
