### ISSUE TITLE
The image_mask in the below image becomes all Falses, when i use LoRA.

### ISSUE THREAD

**Issue by MaxKinny** [2U1/Qwen2-VL-Finetune#2]
![image](https://github.com/user-attachments/assets/15665952-29d7-4b08-aa9e-4c6a1d80665c)

**Comment by 2U1** [comment]
Thanks for the issue. 
Does the latest commit still has the issue?

**Comment by MaxKinny** [comment]
I have modified the data.py file:
[data.zip](https://github.com/user-attachments/files/16981716/data.zip)
Please use the **diff** command to compare the differences.

**Comment by 2U1** [comment]
Maybe your dataset is a bit different from the format I've worte in the README. I have '\n' between the `<image>` token and the text. I use the dataset as LLaVA format.
