### ISSUE TITLE
Error in finetune_video.sh when using deepspeed scripts/zero3_offload.json

### ISSUE THREAD

**Issue by xjohnxjohn** [2U1/Qwen2-VL-Finetune#23]
Hi,
    I use finetune_video.sh with deepspeed scripts/zero3_offload.json, it show error -9 and exit. Can i use finetune_lora to finetune video?

**Comment by 2U1** [comment]
Yes you could. I think -9 is caused by oom so, you could adjust your fps and pixel sizes too.
Also, You could traing with 8bit too.

**Comment by xjohnxjohn** [comment]
Thank you for yours response. Can I use the chat template
<img width="430" alt="image" src="https://github.com/user-attachments/assets/9a399c96-977f-4ffb-9e02-ea2ba1d294fc">
 like this for video? I see the sec/training/data.py, look like not supported the image?

**Comment by 2U1** [comment]
Yes this code only supports the video in mp4, avi, mov or something like that.
However I've inspeceted the model code itsel, it uses as the same as multiimage. So it wouldn't matter if you use the multi-frame video data with multi image.
I'll try to cover up the multi-frame video soon.

**Comment by xjohnxjohn** [comment]
Thank you. I modify finetune_lora_vision to finetune_lora_video, if I use "Qwen2-VL-2B-Instruct", everything pass. When I use "Qwen2-VL-7B-Instruct", it struct in merge_lora.sh. It show the error message "ValueError: Trying to set a tensor of shape torch.Size([151936, 1536]) in "weight" (which has shape torch.Size([152064, 3584])), this looks incorrect."
How to solve this error?

**Comment by 2U1** [comment]
@xjohnxjohn I think you are merging the 2B model weight to the 7B model. 
`torch.Size([151936, 1536])` this is the embed_token weight of 2B model and `torch.Size([152064, 3584]))` this is the embed_token wegith of 7B model. 

Check if you had changed the output directory name when fine tuning 7B after 2B.

**Comment by xjohnxjohn** [comment]
Thank you for you suggestion.
