### ISSUE TITLE
Inference script

### ISSUE THREAD

**Issue by jetwu-create** [2U1/Qwen2-VL-Finetune#6]
Can you release the inference script of this project? Thanks!

**Comment by 2U1** [comment]
Do you need a demo for this?

**Comment by jetwu-create** [comment]
yeah!

**Comment by 2U1** [comment]
@jetwu-create I've made a gradio based web demo for Qwen2-VL. You can upload multi-image, or video data.
The fps for the video data is set to 1.0.

**Comment by 2U1** [comment]
Closing the issue for now updates.
