### ISSUE TITLE
Script about qlora.

### ISSUE THREAD

**Issue by yeppp27** [2U1/Qwen2-VL-Finetune#7]
Hi! Thanks for your great work. Can you provide the script with Qlora fine-tuning?

**Comment by 2U1** [comment]
@R3xpook Thanks for the comment.
@yeppp27 That's right. You can add bits too use qlora.

**Comment by yeppp27** [comment]
Thanks!

**Comment by yeppp27** [comment]
Hi! When  I use deepspeed zero3 with Qlora for sft, I get an error like  "[rank2]: NotImplementedError: Cannot copy out of meta tensor; no data!"

**Comment by 2U1** [comment]
@yeppp27 Sorry, I forgot to tell you. You should use zero2 for QLoRA.

**Comment by yeppp27** [comment]
Thanks! But I got Cuda out of memory for Qlora fine-tuning with zero2 on 72B model. My zero2 config is {
  "fp16": {
    "enabled": "auto",
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 16,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "bf16": {
    "enabled": "auto"
  },
  "train_micro_batch_size_per_gpu": "auto",
  "train_batch_size": "auto",
  "gradient_accumulation_steps": "auto",
  "zero_optimization": {
    "stage": 2,
    "offload_optimizer": {
      "device": "cpu",
      "pin_memory": true
    },
    "offload_param": {
      "device": "cpu",
      "pin_memory": true
    },
    "overlap_comm": true,
    "contiguous_gradients": true,
    "sub_group_size": 1e9,
    "reduce_bucket_size": "auto"
  }
}

**Comment by 2U1** [comment]
I haven't tested 72b model, that I have no resource for it. You could decrease the `pixel_nums` or unset `vision_lr` and `projector_lr`.
