### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by R3xpook** [2U1/Qwen2-VL-Finetune#8]
The single image format is treated as a conversation, correct ? Like a continuous conversation, not each back and forward as single interaction between user and model, and we can't re-use the <image>\n for each message right ?

**Comment by 2U1** [comment]
I can't exactly understand the question. 
Each data with a conversation is treated as a one input. So for a conversation with a single image will pass throgh foraward once and backward once.

**Comment by R3xpook** [comment]
Does the model maintain the context of that image throughout the entire conversation? Or does the image's context get "lost" as more messages are exchanged between the user and the model?

**Comment by 2U1** [comment]
It's maintained. The input is passed in a very long sequence if the conversation has lot of turns.

**Comment by R3xpook** [comment]
Btw any plan to introduce DPO support in the future ?

**Comment by 2U1** [comment]
@R3xpook Not planned, but I'll try.

**Comment by 2U1** [comment]
@R3xpook I've updated the code for DPO.
Sorry it took so long.
